module.exports = {
	routes: {
		ROUTE_CHANGED: 'ROUTE_CHANGED'
	},
	pages: {
		channel: {
			CHANNEL_ADD_TRACKS: 'CHANNEL_ADD_TRACKS',
			TRACK_ADDED_TO_CHANNEL: 'TRACK_ADDED_TO_CHANNEL',
			CHANNEL_STARTED: 'CHANNEL_STARTED'
		}
	},
	server: {
		channel: {
			TRACK_SEARCH_RESPONSE: 'TRACK_SEARCH_RESPONSE'
		}
	}
};